# Generated by Django 5.0.4 on 2024-04-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alter_autordb_options_alter_autordb_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frasedb',
            options={'verbose_name': 'Frase', 'verbose_name_plural': 'Frases'},
        ),
        migrations.AlterModelTable(
            name='frasedb',
            table='Frases',
        ),
    ]
